name: CI

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - parallel:
        - run: cargo clippy --all-targets --all-features --locked -- -D warnings
        - run: cargo test --all-features --locked
        - run: cargo fmt --all -- --check
